name: CI/CD Process

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger CI Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'owner_username',
              repo: 'repository_name',
              workflow_id: 'ci_workflow_id',
              ref: 'main'
            });
            console.log(response.status);

      - name: Trigger CD Workflow
        if: success()
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'owner_username',
              repo: 'repository_name',
              workflow_id: 'cd_workflow_id',
              ref: 'main'
            });
            console.log(response.status);

      - name: Log CI/CD failure
        if: failure()
        run: echo "$(date +"%Y-%m-%d %T"): CI/CD failed for repository ${GITHUB_REPOSITORY}" >> ci-cd-log.txt
