name: CI/CD Process

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rc-test:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rc-test:$(git rev-parse --short HEAD) .
      
      - name: Publish Docker image to Docker Hub
        run: |
          docker logout
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rc-test:latest

      - name: Log CI/CD failure
        if: failure()
        run: |
          echo "$(date +"%Y-%m-%d %T"): CI/CD failed for repository ${GITHUB_REPOSITORY}" >> ci-cd-log.txt


      - name: Download Docker container from Docker Hub
        if: success()
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/rc-test:latest

      - name: Stop and remove existing container (if running)
        run: |
          docker stop rc-test || true
          docker rm rc-test || true
      
      - name: Run Docker container
        run: |
          docker run -d --name rc-test -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/rc-test:latest

      - name: Log CI/CD failure
        if: failure()
        run: |
          echo "$(date +"%Y-%m-%d %T"): CI/CD failed for repository ${GITHUB_REPOSITORY}" >> ci-cd-log.txt
