name: CI/CD Process

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger CI Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'briantpt30',
              repo: 'rc-test',
              workflow_id: '85485999',
              ref: 'main'
            });
            console.log(response.status);

      - name: Trigger CD Workflow
        if: success()
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'briantpt30',
              repo: 'rc-test',
              workflow_id: '85495914',
              ref: 'main'
            });
            console.log(response.status);

      - name: Log CI/CD failure
        if: failure()
        run: |
          echo "$(date +"%Y-%m-%d %T"): CI/CD failed for repository ${GITHUB_REPOSITORY}" >> ci-cd-log.txt
