name: CI Process

on:
  workflow_dispatch:

jobs:
  install-runner:
    runs-on: ubuntu-latest
    name: Install runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          
      - name: Install self hosted runner into this repository
        uses: redhat-actions/openshift-actions-runner-installer@v1
        with:
          github_pat: ${{ secrets.PAT }}
          runner_image: 'quay.io/repository/redhat-github-actions/buildah-runner'
          namspace: 'os-rctest'

  self-hosted-workflow:
    name: Self hosted workflow
    runs-on: [ self-hosted ]
    needs: install-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rc-test:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rc-test:$(git rev-parse --short HEAD) .
      
      - name: Publish Docker image to Docker Hub
        run: |
          docker logout
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rc-test:latest
      
