name: CI Process

on:
  workflow_dispatch:

jobs:
  # build:
  #     name: Build and push image
  #     runs-on: ubuntu-20.04

  #     steps:
  #     - uses: actions/checkout@v2

  #     - name: Build Image
  #       id: build-image
  #       uses: redhat-actions/buildah-build@v2
  #       with:
  #         image: my-app
  #         tags: latest ${{ github.sha }}
  #         containerfiles: |
  #           ./containerfile

  #     # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
  #     # in which case 'username' and 'password' can be omitted.
  #     - name: Push To quay.io
  #       id: push-to-quay
  #       uses: redhat-actions/push-to-registry@v2
  #       with:
  #         image: ${{ steps.build-image.outputs.image }}
  #         tags: ${{ steps.build-image.outputs.tags }}
  #         registry: quay.io/briantpt30
  #         username: briantpt30
  #         password: ${{ secrets.REGISTRY_PASSWORD }}

  #     - name: Print image url
  #       run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  # install-runner:
  #   runs-on: ubuntu-latest
  #   name: Install runner
  #   needs: build
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Authenticate
  #       uses: redhat-actions/oc-login@v1
  #       with:
  #         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
  #         openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          
  #     - name: Install self hosted runner into this repository
  #       uses: redhat-actions/openshift-actions-runner-installer@v1
  #       with:
  #         github_pat: ${{ secrets.PAT }}
  #         runner_image: '${{ steps.push-to-quay.outputs.registry-paths }}'
  #         # runner_tag: 'latest'
  #         namespace: 'os-rctest'
  #         helm_extra_args: --set serviceAccountName=buildah-sa

  self-hosted-workflow:
    name: Self hosted workflow
    runs-on: [ self-hosted ]
    needs: install-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rc-test:latest .
          docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rc-test:$(git rev-parse --short HEAD) .
      
      - name: Publish Docker image to Docker Hub
        run: |
          docker logout
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rc-test:latest
      

